package com.lenta.bp9.platform

object TypeDiscrepanciesConstants {
    const val TYPE_DISCREPANCIES_QUALITY_NORM = "1"
    const val TYPE_DISCREPANCIES_QUALITY_SURPLUS = "2"
    const val TYPE_DISCREPANCIES_QUALITY_PGE_UNDERLOAD = "3"
    const val TYPE_DISCREPANCIES_QUALITY_PGE_MARRIAGE_SHIPMENT = "4"
    const val TYPE_DISCREPANCIES_QUALITY_PGE_WAREHOUSE_MARRIAGE = "5"
    const val TYPE_DISCREPANCIES_REASON_REJECTION_DELIVERY_ERRORS = "4"
    const val TYPE_DISCREPANCIES_REASON_REJECTION_DEFORMATION = "21"
    const val TYPE_DISCREPANCIES_REASON_REJECTION_ERROR_UPD = "100"
}